VERILOG_FILES = ../src/top/zx81_blackicemx.v \
    ../src/sys/ps2.v \
    ../src/sys/scandoubler.v \
    ../src/fpga_zx81.v ../src/memory.v ../src/keyboard.v \
    ../src/cpu/tv80n.v ../src/cpu/tv80_core.v ../src/cpu/tv80_alu.v \
    ../src/cpu/tv80_reg.v ../src/cpu/tv80_mcode.v

PCF_FILE = blackice.pcf

include blackicemx.mk

